### PR TITLE
You should totally go through with these changes...

### PR DESCRIPTION
**Pull request by soarn**

### CODE REVIEW

**Comment by Chew** [comment]
This isn't how ruby works

**Comment by cahcontent** [comment]
I honestly don't know why I didn't close this PR for build fails 8 days ago

**Comment by Chew** [comment]
That's not how PR's work

**Comment by advaith1** [comment]
Aren't you supposed to fix and merge the pr, not just close it because it doesn't work

**Comment by Chew** [comment]
He closed it because it was spam

**Comment by cahcontent** [comment]
I closed it because it's unnecessary, he just wanted the ability to ^join even though invite joining is [already an issue made by the same fellow](https://github.com/CahBots/ircahbot/issues/4)

**Comment by advaith1** [comment]
You said you closed it because it didnt work

**Comment by Chew** [comment]
Actually, he never stated why he closed it until he said it was unnecessary.
Please show us where he said he closed it because it didn't work.

**Comment by advaith1** [comment]
>close this PR for build fails

**Comment by cahcontent** [comment]
I did ask why I didn't close it earlier because the build check failed, which is what ~~they're~~ he's ~~(oops going to start another debate about the usage of They)~~ referring to probably

**Comment by Chew** [comment]
This PR is a mess.

**Review by Chew — COMMENTED** [review]
sux

**Review by cahcontent — COMMENTED** [review]
Understandable, have a nice day

**Comment by advaith1** [comment]
seriously

**Comment by Chew** [comment]
go big or go home

**Review by advaith1 — COMMENTED** [review]
b o r k e d

**Review by cahcontent — COMMENTED** [review]
Go home or go me me big boy

**Pull request closed without merging**
